apiVersion: v1
kind: Service
metadata:
  name: clicker-api-service
  namespace: clicker
  labels:
    app: clicker
spec:
  type: NodePort
  ports:
    - port: 9090
      nodePort: 32010
  selector:
    app: clicker
     