apiVersion: v1
kind: Service
metadata:
  name: clicker-app-service
  namespace: clicker
  labels:
    app: clicker
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32000
  selector:
    app: clicker
     